Vagrant.configure("2") do |config|
  config.vm.box = "fedora/29-cloud-base"
  config.vm.box_version = "29.20181024.1"
  config.disksize.size = '20GB'


# config.vm.define
  (1..4).each do |i|
    config.vm.define "k8s-node#{i}" do |node|
      node.vm.hostname = "k8s-node#{i}"
      node.vm.network "private_network", ip: "192.168.56.2#{i}"

# config.vm.provider
      config.vm.provider "virtualbox" do |vbox|
        vbox.name = "virtualbox-fedora-k8s-node#{i}"
        vbox.memory = "2048"
        vbox.cpus = "2"
      end
    end
  end
end
